# syntax=docker/dockerfile:1.7

# ─────────────────────────────────────────────────────────────────────────────
# Multi-stage Dockerfile for Poray Kemon's Next.js app.
#
# Stages:
#   1. deps      — install ALL deps (incl. dev) for the build
#   2. builder   — generate Prisma client + run `next build` with standalone output
#   3. runner    — minimal node:alpine image with only what we need to run
#
# Final image size target: < 250 MB (vs ~1.5 GB with the naive approach).
# ─────────────────────────────────────────────────────────────────────────────

ARG NODE_VERSION=20.18.0
ARG PNPM_VERSION=10.3.0

# ── deps ─────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION}-alpine AS deps
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm@${PNPM_VERSION}
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma
# Don't run lifecycle scripts (husky, prisma generate) yet — they need files we
# haven't copied. We'll regenerate the Prisma client in the builder stage.
RUN pnpm install --frozen-lockfile --ignore-scripts

# ── builder ───────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION}-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm@${PNPM_VERSION}
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next telemetry in CI; deterministic builds
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Generate the Prisma client (matches our package.json db:generate)
RUN pnpm prisma generate

# `output: 'standalone'` in next.config.ts emits a tiny .next/standalone dir
RUN pnpm build

# ── runner ────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION}-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user for runtime
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 --ingroup nodejs nextjs

# Standalone server bundle (Next.js prunes node_modules to what's actually needed)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Bring the Prisma migrations along so `prisma migrate deploy` works at boot
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
# The Prisma client (incl. the generated query-engine binary) is already
# baked into .next/standalone's node_modules by Next.js when output:
# 'standalone' is enabled. No explicit .prisma copy needed — the runtime
# resolves it via the standalone tree.

USER nextjs
EXPOSE 3000

# Health check (Compose / orchestrator can verify the container is ready)
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1

# server.js is generated by Next's standalone output
CMD ["node", "server.js"]
