// One-shot generator: reads data/du-directory.json and emits a
// prisma migration SQL file that seeds every department + professor
// idempotently. Run once locally, commit the resulting migration.sql,
// merge — Vercel's `prisma migrate deploy` applies it on the next deploy.
//
//   npx --yes tsx scripts/generate-du-seed-migration.ts
//
// Produces: prisma/migrations/<timestamp>_seed_du_directory/migration.sql

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { slugify } from '../lib/slug'

interface Professor {
  nameEn: string
  nameBn?: string | null
  designation?: string | null
}
interface Department {
  nameEn: string
  shortName?: string | null
  professors: Professor[]
}
interface DirectoryFile {
  university: { slug: string; shortName: string }
  faculties: { departments: Department[] }[]
}

type Designation =
  | 'lecturer'
  | 'assistant_professor'
  | 'associate_professor'
  | 'professor'
  | 'adjunct'
  | 'other'
type ProfessorStatus = 'active' | 'retired' | 'unverified'

function parseDesignation(raw: string | null | undefined): {
  designation: Designation
  status: ProfessorStatus
} {
  if (!raw) return { designation: 'other', status: 'active' }
  const s = raw.toLowerCase()
  const status: ProfessorStatus = /\blpr\b|retire/.test(s) ? 'retired' : 'active'
  if (/associate\s+professor/.test(s)) return { designation: 'associate_professor', status }
  if (/assistant\s+professor/.test(s)) return { designation: 'assistant_professor', status }
  if (/\bprofessor\b/.test(s)) return { designation: 'professor', status }
  if (/lecturer/.test(s)) return { designation: 'lecturer', status }
  if (/chair|head\s+of\s+dept/.test(s)) return { designation: 'professor', status }
  if (/adjunct/.test(s)) return { designation: 'adjunct', status }
  return { designation: 'other', status }
}

/** Postgres-safe single-quoted string. */
function sqlStr(v: string | null | undefined): string {
  if (v === null || v === undefined) return 'NULL'
  return `'${v.replace(/'/g, "''")}'`
}

function main() {
  const jsonPath = resolve(process.cwd(), 'data/du-directory.json')
  const doc = JSON.parse(readFileSync(jsonPath, 'utf8')) as DirectoryFile

  const uniSlug = doc.university.slug
  const uniShort = doc.university.shortName.toLowerCase()

  // Track slugs generated across this run so intra-DU duplicates get -2/-3.
  // Cross-uni collisions (across other seeded rows) are caught by the
  // ON CONFLICT (slug) DO NOTHING guard on the INSERT.
  const usedProfSlugs = new Set<string>()
  function uniqueProfSlug(nameEn: string): string {
    const base = slugify(nameEn) || 'professor'
    const withUni = `${base}-${uniShort}`
    for (const candidate of [
      base,
      withUni,
      ...Array.from({ length: 30 }, (_, i) => `${withUni}-${i + 2}`),
    ]) {
      if (!candidate) continue
      if (!usedProfSlugs.has(candidate)) {
        usedProfSlugs.add(candidate)
        return candidate.slice(0, 255)
      }
    }
    throw new Error(`Cannot generate unique slug for "${nameEn}"`)
  }
  function deptSlug(nameEn: string): string {
    return (slugify(nameEn) || 'department').slice(0, 50)
  }

  const lines: string[] = []
  lines.push('-- Seed DU departments + professors from data/du-directory.json.')
  lines.push('-- Generated by scripts/generate-du-seed-migration.ts — do not hand-edit.')
  lines.push('-- Idempotent: departments use ON CONFLICT DO NOTHING on the')
  lines.push('-- (university_id, slug) key; professors use WHERE NOT EXISTS on')
  lines.push('-- (uni_id, dept_id, lower(name_en)) plus ON CONFLICT (slug) as a')
  lines.push('-- last-line defence.')
  lines.push('')
  lines.push('DO $$')
  lines.push('DECLARE')
  lines.push('  v_uni_id INT;')
  lines.push('  v_dept_id INT;')
  lines.push('BEGIN')
  lines.push(`  SELECT id INTO v_uni_id FROM universities WHERE slug = ${sqlStr(uniSlug)};`)
  lines.push(`  IF v_uni_id IS NULL THEN`)
  lines.push(
    `    RAISE NOTICE 'University slug=% not present — skipping DU directory seed', ${sqlStr(uniSlug)};`,
  )
  lines.push('    RETURN;')
  lines.push('  END IF;')
  lines.push('')

  let deptCount = 0
  let profCount = 0

  for (const fac of doc.faculties) {
    for (const dep of fac.departments) {
      const dSlug = deptSlug(dep.nameEn)
      deptCount += 1
      // Departments have TWO unique constraints under the same university:
      // (uni_id, slug) AND (uni_id, short_name). ON CONFLICT can target only
      // one, so pre-check with NOT EXISTS covering both keys, then look up
      // the row (whether we just wrote it or it was already there) by name.
      lines.push(`  -- ── ${dep.shortName ?? '?'} · ${dep.nameEn} ──`)
      lines.push(
        `  INSERT INTO departments (university_id, name_en, short_name, slug, status, created_at)`,
      )
      lines.push(
        `  SELECT v_uni_id, ${sqlStr(dep.nameEn.slice(0, 200))}, ${sqlStr(dep.shortName?.slice(0, 20) ?? null)}, ${sqlStr(dSlug)}, 'verified', NOW()`,
      )
      const shortClause = dep.shortName
        ? ` OR lower(short_name) = lower(${sqlStr(dep.shortName)})`
        : ''
      lines.push(
        `    WHERE NOT EXISTS (SELECT 1 FROM departments WHERE university_id = v_uni_id AND (slug = ${sqlStr(dSlug)} OR lower(name_en) = lower(${sqlStr(dep.nameEn)})${shortClause}));`,
      )
      lines.push('')
      // Look up whichever row now represents this dept — new or existing —
      // by name/short_name/slug so subsequent professor inserts hook in.
      const lookupShort = dep.shortName
        ? ` OR lower(short_name) = lower(${sqlStr(dep.shortName)})`
        : ''
      lines.push(
        `  SELECT id INTO v_dept_id FROM departments WHERE university_id = v_uni_id AND (slug = ${sqlStr(dSlug)} OR lower(name_en) = lower(${sqlStr(dep.nameEn)})${lookupShort}) LIMIT 1;`,
      )
      lines.push('')

      for (const prof of dep.professors) {
        const nameEn = prof.nameEn.trim()
        if (!nameEn) continue
        const { designation, status } = parseDesignation(prof.designation)
        const pSlug = uniqueProfSlug(nameEn)
        profCount += 1

        lines.push(
          `  INSERT INTO professors (university_id, department_id, name_en, name_bn, designation, status, slug, created_at)`,
        )
        lines.push(
          `  SELECT v_uni_id, v_dept_id, ${sqlStr(nameEn.slice(0, 200))}, ${sqlStr(prof.nameBn?.slice(0, 200) ?? null)}, '${designation}'::"Designation", '${status}'::"ProfessorStatus", ${sqlStr(pSlug)}, NOW()`,
        )
        lines.push(
          `    WHERE NOT EXISTS (SELECT 1 FROM professors WHERE university_id = v_uni_id AND department_id = v_dept_id AND lower(name_en) = lower(${sqlStr(nameEn)}))`,
        )
        lines.push(`  ON CONFLICT (slug) DO NOTHING;`)
      }
      lines.push('')
    }
  }

  lines.push('END $$;')

  const ts = '20260809120000'
  const migrationDir = resolve(process.cwd(), `prisma/migrations/${ts}_seed_du_directory`)
  const outPath = resolve(migrationDir, 'migration.sql')
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, lines.join('\n') + '\n', 'utf8')

  console.log(`Wrote ${outPath}`)
  console.log(`Departments: ${deptCount}`)
  console.log(`Professors:  ${profCount}`)
  console.log(`Lines:       ${lines.length}`)
}

main()
